name: harmonica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  intl: ^0.17.0
  supabase_flutter: ^2.0.1
  custom_route_transitions_nan: ^0.0.3
  email_validator: '^2.1.16'
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.0.8
  flutter_swipe: ^1.0.1
  image_picker: ^1.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/LogoPositivo.png
    - assets/images/Isotipo.png
    - assets/images/Isotipo2.png
    - assets/images/userGenericImage.jpg
